title = Instructor Datum Filter
desc = This component provides a way to issue dynamic instructions based on expressions.

instructorConfigs.key = Instructor Configurations
instructorConfigs.desc = The list of instruction rule configurations.
