expressions.url = https://solarnetwork.github.io/solarnode-handbook/users/datum-filters/instructor/#expressions

predicate.expression.key = Predicate
predicate.expression.desc = The <a href="{0}" title="Expression language guide" target="_blank">expression <i \
	class="bi bi-box-arrow-up-right"></i></a> that must evaluate to <code>true</code> to generate the configured instruction. \
	See the <a href="{1}" title="Expression guide" target="_blank">expression guide <i class="bi bi-box-arrow-up-right"></i></a> for more info.

predicate.expressionServiceId.key = Expression Language
predicate.expressionServiceId.desc = The expression language <b>Predicate</b> is written in.

instructions.key = Instructions
instructions.desc = A list of instructions to execute when the <b>Predicate</b> evaluates to <code>true</code>.
