expressions.url = https://solarnetwork.github.io/solarnode-handbook/users/datum-filters/instructor/#expressions

predicate.expression.key = Predicate
predicate.expression.desc = The <a href="{0}" title="Expression language guide" target="_blank">expression <i \
	class="bi bi-box-arrow-up-right"></i></a> that must evaluate to <code>true</code> to generate the configured instruction. \
	See the <a href="{1}" title="Expression guide" target="_blank">expression guide <i class="bi bi-box-arrow-up-right"></i></a> for more info.

predicate.expressionServiceId.key = Expression Language
predicate.expressionServiceId.desc = The expression language <b>Predicate</b> is written in.


topic.key = Instruction Topic
topic.desc = The instruction topic to generate when the <b>Predicate</b> evaluates to <code>true</code>.

parameters.key = Instruction Parameters
parameters.desc = A list of parameters to include in the generated instruction.

parametersItem.name.key = Parameter Name
parametersItem.name.desc = The instruction parameter name.

parametersItem.expression.key = Parameter Value
parametersItem.expression.desc = The instruction parameter value.

parametersItem.expressionServiceId.key = Parameter Expression Language
parametersItem.expressionServiceId.desc = The expression language <b>Parameter Value</b> is written in, \
	or omit to treat <b>Parameter Value</b> as plain text.

responses.key = Result Expressions
responses.desc = A list of expressions to evaluate on the instruction result.

responsesItem.name.key = Result Datum Property
responsesItem.name.desc = A datum property name to save the expression result to. Leave empty to \
	evaluate the expression without saving any datum property.

responsesItem.datumPropertyTypeKey.key = Result Datum Property Type
responsesItem.datumPropertyTypeKey.desc = The datum property type to save the expression result as.

responsesItem.expression.key = Result Expression
responsesItem.expression.desc = The expression to evaluate.

responsesItem.expressionServiceId.key = Result Expression Language
responsesItem.expressionServiceId.desc = The expression language <b>Result Expression</b> is written in.
