topic.key = Instruction Topic
topic.desc = The instruction topic to generate .

parameters.key = Instruction Parameters
parameters.desc = A list of parameters to include in the generated instruction.

parametersItem.name.key = Parameter Name
parametersItem.name.desc = The instruction parameter name.

parametersItem.expression.key = Parameter Value
parametersItem.expression.desc = The instruction parameter value.

parametersItem.expressionServiceId.key = Parameter Expression Language
parametersItem.expressionServiceId.desc = The expression language <b>Parameter Value</b> is written in, \
	or omit to treat <b>Parameter Value</b> as plain text.

responses.key = Result Expressions
responses.desc = A list of expressions to evaluate on the instruction result.

responsesItem.name.key = Result Datum Property
responsesItem.name.desc = A datum property name to save the expression result to. Leave empty to \
	evaluate the expression without saving any datum property.

responsesItem.datumPropertyTypeKey.key = Result Datum Property Type
responsesItem.datumPropertyTypeKey.desc = The datum property type to save the expression result as.

responsesItem.expression.key = Result Expression
responsesItem.expression.desc = The expression to evaluate.

responsesItem.expressionServiceId.key = Result Expression Language
responsesItem.expressionServiceId.desc = The expression language <b>Result Expression</b> is written in.
